spring:
  config:
    import:
      - optional:file:.env[.properties]
  application:
    name: notification-service
  kafka:
    bootstrap-servers:
      - ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}  
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:857}
    username: ${SMTP_USER}
    password: ${SMTP_PASS}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true

server:
  port: ${PORT:8007}

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 15
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
